export type FieldEntry = { key: string; label: string; x: number; y: number; page?: number }

export const FORM_FIELDS: Record<string, FieldEntry[]> = {
  DISABILITY_CLAIM: [
    { key: "name",           label: "성명 (근로자명)",     x: 157, y: 670 },
    { key: "birthY1",        label: "생년 Y1",             x: 286, y: 671 },
    { key: "birthY2",        label: "생년 Y2",             x: 303, y: 671 },
    { key: "birthY3",        label: "생년 Y3",             x: 320, y: 671 },
    { key: "birthY4",        label: "생년 Y4",             x: 337, y: 671 },
    { key: "birthM1",        label: "생월 M1",             x: 368, y: 671 },
    { key: "birthM2",        label: "생월 M2",             x: 385, y: 671 },
    { key: "birthD1",        label: "생일 D1",             x: 415, y: 671 },
    { key: "birthD2",        label: "생일 D2",             x: 433, y: 671 },
    { key: "injY1",          label: "재해일 y1",           x: 103, y: 639 },
    { key: "injY2",          label: "재해일 y2",           x: 120, y: 639 },
    { key: "injY3",          label: "재해일 y3",           x: 137, y: 639 },
    { key: "injY4",          label: "재해일 y4",           x: 153, y: 639 },
    { key: "injM1",          label: "재해월 m1",           x: 185, y: 639 },
    { key: "injM2",          label: "재해월 m2",           x: 202, y: 639 },
    { key: "injD1",          label: "재해일 d1",           x: 233, y: 639 },
    { key: "injD2",          label: "재해일 d2",           x: 250, y: 639 },
    { key: "todayYear",      label: "오늘 연도",            x: 392, y: 340 },
    { key: "todayMonth",     label: "오늘 월",              x: 440, y: 340 },
    { key: "todayDay",       label: "오늘 일",              x: 473, y: 340 },
    { key: "ptName",         label: "청구인 성명",          x: 325, y: 328 },
    { key: "ptPhone",        label: "청구인 연락처",        x: 483, y: 327 },
    { key: "mgrName",        label: "대리인 성명",          x: 325, y: 313 },
    { key: "mgrTel",         label: "대리인 Tel",           x: 483, y: 313 },
    { key: "kwc",            label: "관할공단",             x: 299, y: 93  },
    { key: "bankChangeYes",  label: "수령계좌변경 예",      x: 287, y: 619 },
    { key: "bankChangeNo",   label: "수령계좌변경 아니오",  x: 362, y: 619 },
    { key: "bankName",       label: "은행명",               x: 189, y: 600 },
    { key: "bankAccount",    label: "계좌번호",             x: 169, y: 581 },
    { key: "bankHolder",     label: "예금주",               x: 470, y: 581 },
    { key: "bankTypeNormal", label: "보통계좌 체크",        x: 120, y: 561 },
    { key: "bankTypeSpecial",label: "전용계좌 체크",        x: 222, y: 562 },
    { key: "confirm1Yes",    label: "확인①예",              x: 434, y: 539 },
    { key: "confirm1No",     label: "확인①아니오",          x: 483, y: 539 },
    { key: "confirm2Yes",    label: "확인②예",              x: 428, y: 509 },
    { key: "confirm2No",     label: "확인②아니오",          x: 469, y: 509 },
    { key: "receiptDate",    label: "수령일자",             x: 127, y: 464 },
    { key: "receiptAmount",  label: "수령금액",             x: 209, y: 465 },
    { key: "receiptPayer",   label: "지급한자",             x: 297, y: 466 },
    { key: "transferCost",   label: "이송비용",             x: 183, y: 440 },
    { key: "transferDetail", label: "이송비산출내역",       x: 317, y: 440 },
    { key: "compPart",       label: "합병증부위",           x: 207, y: 396 },
    { key: "compHospital",   label: "합병증의료기관",       x: 453, y: 396 },
  ],
  NOISE_WORK_CONFIRM: [
    { key: "name",          label: "성명",            x: 270, y: 693 },
    { key: "jumin1",        label: "주민번호 1",       x: 278, y: 670 },
    { key: "jumin2",        label: "주민번호 2",       x: 295, y: 670 },
    { key: "jumin3",        label: "주민번호 3",       x: 312, y: 670 },
    { key: "jumin4",        label: "주민번호 4",       x: 329, y: 670 },
    { key: "jumin5",        label: "주민번호 5",       x: 346, y: 670 },
    { key: "jumin6",        label: "주민번호 6",       x: 363, y: 670 },
    { key: "jumin7",        label: "주민번호 7",       x: 389, y: 670 },
    { key: "jumin8",        label: "주민번호 8",       x: 406, y: 670 },
    { key: "jumin9",        label: "주민번호 9",       x: 422, y: 670 },
    { key: "jumin10",       label: "주민번호 10",      x: 440, y: 670 },
    { key: "jumin11",       label: "주민번호 11",      x: 456, y: 670 },
    { key: "jumin12",       label: "주민번호 12",      x: 474, y: 670 },
    { key: "jumin13",       label: "주민번호 13",      x: 491, y: 670 },
    { key: "address",       label: "주소",             x: 164, y: 645 },
    { key: "checkEmployed", label: "재직 체크",        x: 316, y: 620 },
    { key: "checkRetired",  label: "퇴직 체크",        x: 401, y: 620 },
    { key: "todayYear",     label: "오늘 연도",        x: 204, y: 143 },
    { key: "todayMonth",    label: "오늘 월",          x: 275, y: 143 },
    { key: "todayDay",      label: "오늘 일",          x: 331, y: 143 },
    { key: "ptName",        label: "청구인 성명",      x: 268, y: 118 },
    { key: "ptPhone",       label: "청구인 연락처",    x: 431, y: 118 },
    { key: "mgrName",       label: "대리인 성명",      x: 268, y: 106 },
    { key: "mgrTel",        label: "대리인 Tel",       x: 431, y: 106 },
    { key: "appendixCheck", label: "별지사용 체크",    x: 367, y: 374 },
    // 추가 필드 — 좌표는 관리자 페이지에서 지정
    { key: "hireDate",        label: "채용일자",         x: 0,   y: 0 },
    { key: "resignDate",      label: "퇴직일자",         x: 0,   y: 0 },
    { key: "workStartTime",   label: "출근시간",         x: 0,   y: 0 },
    { key: "workEndTime",     label: "퇴근시간",         x: 0,   y: 0 },
    { key: "jobTitle",        label: "직종",             x: 0,   y: 0 },
    { key: "isOwner",         label: "사업주여부",       x: 0,   y: 0 },
    { key: "isRelative",      label: "친인척여부",       x: 0,   y: 0 },
    { key: "workerType",      label: "근로자 유형",      x: 0,   y: 0 },
    { key: "workplaceName",   label: "사업장명",         x: 0,   y: 0 },
    { key: "workplaceRegNo",  label: "사업장관리번호",   x: 0,   y: 0 },
    { key: "workplaceAddress",label: "사업장 주소",      x: 0,   y: 0 },
  ],
  AGENT_APPOINTMENT: [
    { key: "caseTitle",   label: "사건명",           x: 184, y: 664 },
    { key: "name",        label: "성명 (근로자)",    x: 193, y: 629 },
    { key: "birthDate",   label: "생년월일",         x: 452, y: 629 },
    { key: "address",     label: "주소 (근로자)",    x: 186, y: 599 },
    { key: "phone",       label: "연락처 (근로자)",  x: 372, y: 574 },
    { key: "mgrBranch",   label: "상호 (지사명)",    x: 222, y: 505 },
    { key: "mgrLicense",  label: "등록번호",         x: 470, y: 505 },
    { key: "mgrName",     label: "대리인 성명",      x: 250, y: 460 },
    { key: "mgrJobTitle", label: "대리인 직책",      x: 477, y: 460 },
    { key: "mgrAddress",  label: "대리인 주소",      x: 186, y: 425 },
    { key: "mgrHP",       label: "대리인 H.P",       x: 227, y: 400 },
    { key: "mgrTel",      label: "대리인 Tel",       x: 342, y: 400 },
    { key: "mgrFax",      label: "대리인 Fax",       x: 450, y: 391 },
    { key: "scope",       label: "대리의 범위",      x: 271, y: 356 },
    { key: "injDate",     label: "선임일 (재해일)",  x: 199, y: 315 },
    { key: "todayYear",   label: "오늘 연도",        x: 340, y: 203 },
    { key: "todayMonth",  label: "오늘 월",          x: 412, y: 203 },
    { key: "todayDay",    label: "오늘 일",          x: 461, y: 203 },
    { key: "ptName",      label: "신고인 성명",      x: 367, y: 173 },
    { key: "kwc",         label: "관할공단",         x: 346, y: 140 },
  ],
  POWER_OF_ATTORNEY: [
    { key: "mgrBranch",   label: "법인명 (지사)",    x: 240, y: 657 },
    { key: "mgrAddress",  label: "소재지",           x: 240, y: 638 },
    { key: "mgrTel",      label: "전화",             x: 240, y: 620 },
    { key: "mgrFax",      label: "FAX",              x: 240, y: 602 },
    { key: "mgrLicense",  label: "등록번호",         x: 295, y: 585 },
    { key: "mgrName",     label: "성명 (노무사)",    x: 233, y: 567 },
    { key: "todayYear",   label: "오늘 연도",        x: 345, y: 280 },
    { key: "todayMonth",  label: "오늘 월",          x: 409, y: 280 },
    { key: "todayDay",    label: "오늘 일",          x: 468, y: 280 },
    { key: "name",        label: "성명 (근로자)",    x: 285, y: 234 },
    { key: "ssn",         label: "주민번호",         x: 285, y: 206 },
    { key: "address",     label: "주소 (근로자)",    x: 285, y: 176 },
  ],
  SPECIAL_CLINIC: [
    { key: "name",       label: "성명",             x:  93, y: 676 },
    { key: "ssn1",       label: "주민번호 1",        x: 173, y: 676 },
    { key: "ssn2",       label: "주민번호 2",        x: 190, y: 676 },
    { key: "ssn3",       label: "주민번호 3",        x: 206, y: 676 },
    { key: "ssn4",       label: "주민번호 4",        x: 223, y: 676 },
    { key: "ssn5",       label: "주민번호 5",        x: 240, y: 676 },
    { key: "ssn6",       label: "주민번호 6",        x: 257, y: 676 },
    { key: "ssn7",       label: "주민번호 7",        x: 276, y: 676 },
    { key: "ssn8",       label: "주민번호 8",        x:   0, y:   0 },
    { key: "ssn9",       label: "주민번호 9",        x:   0, y:   0 },
    { key: "ssn10",      label: "주민번호 10",       x:   0, y:   0 },
    { key: "ssn11",      label: "주민번호 11",       x:   0, y:   0 },
    { key: "ssn12",      label: "주민번호 12",       x:   0, y:   0 },
    { key: "ssn13",      label: "주민번호 13",       x:   0, y:   0 },
    { key: "injY1",      label: "재해일 y1",         x: 399, y: 676 },
    { key: "injY2",      label: "재해일 y2",         x: 416, y: 676 },
    { key: "injY3",      label: "재해일 y3",         x: 432, y: 676 },
    { key: "injY4",      label: "재해일 y4",         x: 450, y: 676 },
    { key: "injM1",      label: "재해월 m1",         x: 474, y: 676 },
    { key: "injM2",      label: "재해월 m2",         x: 491, y: 676 },
    { key: "injD1",      label: "재해일 d1",         x: 515, y: 676 },
    { key: "injD2",      label: "재해일 d2",         x: 533, y: 676 },
    { key: "address",    label: "주소",              x: 148, y: 642 },
    { key: "phone",      label: "연락처",            x: 465, y: 640 },
    { key: "clinicName", label: "특진의료기관명",    x: 171, y: 524 },
    { key: "clinicAddr", label: "특진의료기관 주소", x: 364, y: 524 },
    { key: "clinic2Name",label: "특진의료기관2명",   x:   0, y:   0 },
    { key: "clinic2Addr",label: "특진의료기관2주소", x:   0, y:   0 },
    { key: "clinic3Name",label: "특진의료기관3명",   x:   0, y:   0 },
    { key: "clinic3Addr",label: "특진의료기관3주소", x:   0, y:   0 },
    { key: "todayYear",  label: "오늘 연도",         x: 338, y: 195 },
    { key: "todayMonth", label: "오늘 월",           x: 385, y: 195 },
    { key: "todayDay",   label: "오늘 일",           x: 418, y: 195 },
    { key: "ptName",     label: "작성인 성명",       x: 174, y: 182 },
    { key: "ptPhone",    label: "작성인 연락처",     x: 503, y: 182 },
    { key: "mgrName",    label: "대리인 성명",       x: 174, y: 165 },
    { key: "mgrTel",     label: "대리인 Tel",        x: 503, y: 164 },
    { key: "kwc",        label: "관할공단",          x: 133, y:  69 },
  ],
  EXPERT_CLINIC: [
    { key: "name",       label: "성명",             x:  93, y: 676 },
    { key: "ssn1",       label: "주민번호 1",        x: 173, y: 676 },
    { key: "ssn2",       label: "주민번호 2",        x: 190, y: 676 },
    { key: "ssn3",       label: "주민번호 3",        x: 206, y: 676 },
    { key: "ssn4",       label: "주민번호 4",        x: 223, y: 676 },
    { key: "ssn5",       label: "주민번호 5",        x: 240, y: 676 },
    { key: "ssn6",       label: "주민번호 6",        x: 257, y: 676 },
    { key: "ssn7",       label: "주민번호 7",        x: 276, y: 676 },
    { key: "ssn8",       label: "주민번호 8",        x:   0, y:   0 },
    { key: "ssn9",       label: "주민번호 9",        x:   0, y:   0 },
    { key: "ssn10",      label: "주민번호 10",       x:   0, y:   0 },
    { key: "ssn11",      label: "주민번호 11",       x:   0, y:   0 },
    { key: "ssn12",      label: "주민번호 12",       x:   0, y:   0 },
    { key: "ssn13",      label: "주민번호 13",       x:   0, y:   0 },
    { key: "injY1",      label: "재해일 y1",         x: 399, y: 676 },
    { key: "injY2",      label: "재해일 y2",         x: 416, y: 676 },
    { key: "injY3",      label: "재해일 y3",         x: 432, y: 676 },
    { key: "injY4",      label: "재해일 y4",         x: 450, y: 676 },
    { key: "injM1",      label: "재해월 m1",         x: 474, y: 676 },
    { key: "injM2",      label: "재해월 m2",         x: 491, y: 676 },
    { key: "injD1",      label: "재해일 d1",         x: 515, y: 676 },
    { key: "injD2",      label: "재해일 d2",         x: 533, y: 676 },
    { key: "address",    label: "주소",              x: 148, y: 642 },
    { key: "phone",      label: "연락처",            x: 465, y: 640 },
    { key: "clinicName", label: "특진의료기관명",    x: 171, y: 524 },
    { key: "clinicAddr", label: "특진의료기관 주소", x: 364, y: 524 },
    { key: "clinic2Name",label: "특진의료기관2명",   x:   0, y:   0 },
    { key: "clinic2Addr",label: "특진의료기관2주소", x:   0, y:   0 },
    { key: "clinic3Name",label: "특진의료기관3명",   x:   0, y:   0 },
    { key: "clinic3Addr",label: "특진의료기관3주소", x:   0, y:   0 },
    { key: "todayYear",  label: "오늘 연도",         x: 338, y: 195 },
    { key: "todayMonth", label: "오늘 월",           x: 385, y: 195 },
    { key: "todayDay",   label: "오늘 일",           x: 418, y: 195 },
    { key: "ptName",     label: "작성인 성명",       x: 174, y: 182 },
    { key: "ptPhone",    label: "작성인 연락처",     x: 503, y: 182 },
    { key: "mgrName",    label: "대리인 성명",       x: 174, y: 165 },
    { key: "mgrTel",     label: "대리인 Tel",        x: 503, y: 164 },
    { key: "kwc",        label: "관할공단",          x: 133, y:  69 },
  ],
  WORK_HISTORY: [
    { key: "name",       label: "성명 (p1)",          x: 172, y: 638, page: 1 },
    { key: "phone",      label: "연락처 (p1)",         x: 174, y: 609, page: 1 },
    { key: "address",    label: "주소 (p1)",           x: 174, y: 582, page: 1 },
    { key: "totalDur",   label: "합계 근무기간 (p2)",  x: 109, y: 687, page: 2 },
    { key: "todayYear",  label: "오늘 연도 (p3)",      x: 219, y: 309, page: 3 },
    { key: "todayMonth", label: "오늘 월 (p3)",        x: 282, y: 308, page: 3 },
    { key: "todayDay",   label: "오늘 일 (p3)",        x: 329, y: 308, page: 3 },
    { key: "ptName",     label: "청구인 성명 (p3)",    x: 283, y: 267, page: 3 },
    { key: "ptPhone",    label: "청구인 연락처 (p3)",  x: 485, y: 267, page: 3 },
    { key: "mgrName",    label: "대리인 성명 (p3)",    x: 283, y: 222, page: 3 },
    { key: "mgrTel",     label: "대리인 Tel (p3)",     x: 485, y: 222, page: 3 },
  ],
  INFO_DISCLOSURE: [
    { key: "claimantName",  label: "청구인성명",       x: 108, y: 711 },
    { key: "agentSsn",      label: "주민번호",         x: 338, y: 711 },
    { key: "officeAddress", label: "주소",             x: 108, y: 686 },
    { key: "bizRegNo",      label: "사업자등록번호",   x: 338, y: 686 },
    { key: "officeTel",     label: "전화번호",         x: 108, y: 649 },
    { key: "officeFax",     label: "팩스번호",         x: 225, y: 649 },
    { key: "email",         label: "이메일",           x: 338, y: 649 },
    { key: "content",       label: "청구내용",         x: 108, y: 561 },
    { key: "submitYear",    label: "년",               x: 384, y: 321 },
    { key: "submitMonth",   label: "월",               x: 430, y: 321 },
    { key: "submitDay",     label: "일",               x: 470, y: 321 },
    { key: "agentName",     label: "청구인서명",       x: 108, y: 304 },
    { key: "kwc",           label: "관할공단명",        x: 100, y: 286 },
  ],
  LABOR_ATTORNEY_RECORD: [
    { key: "branchName",     label: "상호(지사명)",    x: 120.5, y: 695 },
    { key: "ptName",         label: "성명(대표자)",    x: 132.5, y: 670 },
    { key: "birthDate",      label: "생년월일",        x: 399,   y: 671 },
    { key: "address",        label: "주소",            x: 149,   y: 642 },
    { key: "commissionDate", label: "직무위촉연월일",  x: 163,   y: 609 },
    { key: "feeContract",    label: "수수료 계약금",   x: 268,   y: 581 },
    { key: "feeAdvance",     label: "착수금",          x: 493,   y: 580 },
    { key: "jobSummary",     label: "직무 요지",       x: 67,    y: 516 },
    { key: "result",         label: "처리 결과",       x: 66,    y: 366 },
    { key: "note",           label: "특기사항",        x: 66,    y: 203 },
  ],
  THIRD_PARTY_INFO: [
    { key: "year",       label: "년",           x: 245, y: 99  },
    { key: "month",      label: "월",           x: 287, y: 99  },
    { key: "day",        label: "일",           x: 325, y: 99  },
    { key: "ssn",        label: "주민등록번호", x: 100, y: 79  },
    { key: "ptName",     label: "성명",         x: 250, y: 79  },
    { key: "yesCheck",   label: "예 체크",      x: 365, y: 126 },
  ],
  MEDICAL_BENEFIT: [
    { key: "ptName",         label: "성명",          x: 65,  y: 684 },
    { key: "address",        label: "주소",          x: 66,  y: 650 },
    { key: "phone",          label: "휴대전화",      x: 353, y: 665 },
    { key: "workplaceCheck", label: "질병 체크",     x: 254, y: 347 },
    { key: "workplaceName",  label: "사업장명",      x: 130, y: 479 },
    { key: "workplaceAddr",  label: "사업장주소",    x: 106, y: 436 },
    { key: "claimYear",      label: "신청년",        x: 236, y: 86  },
    { key: "claimMonth",     label: "신청월",        x: 280, y: 86  },
    { key: "claimDay",       label: "신청일",        x: 310, y: 86  },
    { key: "claimantName",   label: "신청인",        x: 340, y: 70  },
    { key: "agentName",      label: "대리인",        x: 340, y: 54  },
    { key: "kwc",            label: "귀하",          x: 200, y: 40  },
    { key: "ssn1",           label: "주민번호 1",    x: 0,   y: 0   },
    { key: "ssn2",           label: "주민번호 2",    x: 0,   y: 0   },
    { key: "ssn3",           label: "주민번호 3",    x: 0,   y: 0   },
    { key: "ssn4",           label: "주민번호 4",    x: 0,   y: 0   },
    { key: "ssn5",           label: "주민번호 5",    x: 0,   y: 0   },
    { key: "ssn6",           label: "주민번호 6",    x: 0,   y: 0   },
    { key: "ssn7",           label: "주민번호 7",    x: 0,   y: 0   },
    { key: "ssn8",           label: "주민번호 8",    x: 0,   y: 0   },
    { key: "ssn9",           label: "주민번호 9",    x: 0,   y: 0   },
    { key: "ssn10",          label: "주민번호 10",   x: 0,   y: 0   },
    { key: "ssn11",          label: "주민번호 11",   x: 0,   y: 0   },
    { key: "ssn12",          label: "주민번호 12",   x: 0,   y: 0   },
    { key: "ssn13",          label: "주민번호 13",   x: 0,   y: 0   },
    { key: "injY1",          label: "재해발생일 년1", x: 0,  y: 0   },
    { key: "injY2",          label: "재해발생일 년2", x: 0,  y: 0   },
    { key: "injY3",          label: "재해발생일 년3", x: 0,  y: 0   },
    { key: "injY4",          label: "재해발생일 년4", x: 0,  y: 0   },
    { key: "injM1",          label: "재해발생일 월1", x: 0,  y: 0   },
    { key: "injM2",          label: "재해발생일 월2", x: 0,  y: 0   },
    { key: "injD1",          label: "재해발생일 일1", x: 0,  y: 0   },
    { key: "injD2",          label: "재해발생일 일2", x: 0,  y: 0   },
  ],
  SICK_LEAVE_BENEFIT: [
    { key: "ptName",          label: "성명",          x: 150, y: 688 },
    { key: "ssn1",            label: "주민번호 1",    x: 0,   y: 0   },
    { key: "ssn2",            label: "주민번호 2",    x: 0,   y: 0   },
    { key: "ssn3",            label: "주민번호 3",    x: 0,   y: 0   },
    { key: "ssn4",            label: "주민번호 4",    x: 0,   y: 0   },
    { key: "ssn5",            label: "주민번호 5",    x: 0,   y: 0   },
    { key: "ssn6",            label: "주민번호 6",    x: 0,   y: 0   },
    { key: "ssn7",            label: "주민번호 7",    x: 0,   y: 0   },
    { key: "ssn8",            label: "주민번호 8",    x: 0,   y: 0   },
    { key: "ssn9",            label: "주민번호 9",    x: 0,   y: 0   },
    { key: "ssn10",           label: "주민번호 10",   x: 0,   y: 0   },
    { key: "ssn11",           label: "주민번호 11",   x: 0,   y: 0   },
    { key: "ssn12",           label: "주민번호 12",   x: 0,   y: 0   },
    { key: "ssn13",           label: "주민번호 13",   x: 0,   y: 0   },
    { key: "bankName",        label: "은행명",        x: 0,   y: 0   },
    { key: "bankAccount",     label: "수령계좌",      x: 95,  y: 583 },
    { key: "accountHolder",   label: "예금주",        x: 380, y: 583 },
    { key: "claimStartYear",  label: "청구시작년",    x: 95,  y: 518 },
    { key: "claimStartMonth", label: "청구시작월",    x: 140, y: 518 },
    { key: "claimStartDay",   label: "청구시작일",    x: 178, y: 518 },
    { key: "claimEndYear",    label: "청구종료년",    x: 260, y: 518 },
    { key: "claimEndMonth",   label: "청구종료월",    x: 305, y: 518 },
    { key: "claimEndDay",     label: "청구종료일",    x: 343, y: 518 },
    { key: "submitYear",      label: "신청년",        x: 230, y: 271 },
    { key: "submitMonth",     label: "신청월",        x: 270, y: 271 },
    { key: "submitDay",       label: "신청일",        x: 305, y: 271 },
    { key: "claimantName",    label: "청구인",        x: 195, y: 255 },
    { key: "claimantPhone",   label: "청구인전화",    x: 340, y: 255 },
    { key: "agentName",       label: "대리인",        x: 195, y: 239 },
    { key: "agentPhone",      label: "대리인전화",    x: 340, y: 239 },
    { key: "kwc",             label: "귀하",          x: 205, y: 125 },
    { key: "birthY1",         label: "생년월일 년1",  x: 0,   y: 0   },
    { key: "birthY2",         label: "생년월일 년2",  x: 0,   y: 0   },
    { key: "birthY3",         label: "생년월일 년3",  x: 0,   y: 0   },
    { key: "birthY4",         label: "생년월일 년4",  x: 0,   y: 0   },
    { key: "birthM1",         label: "생년월일 월1",  x: 0,   y: 0   },
    { key: "birthM2",         label: "생년월일 월2",  x: 0,   y: 0   },
    { key: "birthD1",         label: "생년월일 일1",  x: 0,   y: 0   },
    { key: "birthD2",         label: "생년월일 일2",  x: 0,   y: 0   },
    { key: "injY1",           label: "재해발생일 년1", x: 0,  y: 0   },
    { key: "injY2",           label: "재해발생일 년2", x: 0,  y: 0   },
    { key: "injY3",           label: "재해발생일 년3", x: 0,  y: 0   },
    { key: "injY4",           label: "재해발생일 년4", x: 0,  y: 0   },
    { key: "injM1",           label: "재해발생일 월1", x: 0,  y: 0   },
    { key: "injM2",           label: "재해발생일 월2", x: 0,  y: 0   },
    { key: "injD1",           label: "재해발생일 일1", x: 0,  y: 0   },
    { key: "injD2",           label: "재해발생일 일2", x: 0,  y: 0   },
  ],
  INFO_DISCLOSURE_PROXY: [
    { key: "ptName",       label: "위임인성명",     x: 112, y: 732 },
    { key: "ptSsn",        label: "위임인주민번호", x: 342, y: 732 },
    { key: "ptAddress",    label: "위임인주소",     x: 112, y: 698 },
    { key: "agentName",    label: "수임인성명",     x: 112, y: 660 },
    { key: "agentSsn",     label: "수임인주민번호", x: 342, y: 660 },
    { key: "agentAddress", label: "수임인주소",     x: 112, y: 643 },
    { key: "submitYear",        label: "년",                 x: 350, y: 142 },
    { key: "submitMonth",       label: "월",                 x: 395, y: 142 },
    { key: "submitDay",         label: "일",                 x: 430, y: 142 },
    { key: "ptSign",            label: "위임인서명",         x: 333, y: 110 },
    { key: "infoContent",       label: "정보 내용",          x: 0,   y: 0   },
  ],
  PENSION_CHOICE: [
    { key: "submitYear",  label: "년",         x: 236, y: 93 },
    { key: "submitMonth", label: "월",         x: 282, y: 93 },
    { key: "submitDay",   label: "일",         x: 318, y: 93 },
    { key: "signName",    label: "확인자성명", x: 310, y: 78 },
  ],
  BEREAVED_CLAIM: [
    { key: "workplaceName",  label: "사업장명",   x: 355, y: 694 },
    { key: "workplaceArea",  label: "소재지",     x: 437, y: 684 },
    { key: "deceasedName",   label: "재해자성명", x: 156, y: 656 },
    { key: "ssn1",           label: "주민번호 1",  x: 0,   y: 0   },
    { key: "ssn2",           label: "주민번호 2",  x: 0,   y: 0   },
    { key: "ssn3",           label: "주민번호 3",  x: 0,   y: 0   },
    { key: "ssn4",           label: "주민번호 4",  x: 0,   y: 0   },
    { key: "ssn5",           label: "주민번호 5",  x: 0,   y: 0   },
    { key: "ssn6",           label: "주민번호 6",  x: 0,   y: 0   },
    { key: "ssn7",           label: "주민번호 7",  x: 0,   y: 0   },
    { key: "ssn8",           label: "주민번호 8",  x: 0,   y: 0   },
    { key: "ssn9",           label: "주민번호 9",  x: 0,   y: 0   },
    { key: "ssn10",          label: "주민번호 10", x: 0,   y: 0   },
    { key: "ssn11",          label: "주민번호 11", x: 0,   y: 0   },
    { key: "ssn12",          label: "주민번호 12", x: 0,   y: 0   },
    { key: "ssn13",          label: "주민번호 13", x: 0,   y: 0   },
    { key: "address",        label: "주소",       x: 156, y: 628 },
    { key: "occupation",     label: "직종",       x: 437, y: 618 },
    { key: "funeralDate",    label: "장례실행일", x: 430, y: 466 },
    { key: "bankAccount",    label: "수령계좌",   x: 150, y: 356 },
    { key: "accountHolder",  label: "예금주",     x: 390, y: 356 },
    { key: "submitYear",     label: "신청년",     x: 160, y: 131 },
    { key: "submitMonth",    label: "신청월",     x: 200, y: 131 },
    { key: "submitDay",      label: "신청일",     x: 235, y: 131 },
    { key: "claimantName",   label: "청구인",     x: 130, y: 115 },
    { key: "agentName",      label: "대리인",     x: 130, y: 99  },
    { key: "kwc",            label: "귀하",          x: 209, y: 83  },
    { key: "injY1",          label: "재해발생일 년1", x: 0,  y: 0   },
    { key: "injY2",          label: "재해발생일 년2", x: 0,  y: 0   },
    { key: "injY3",          label: "재해발생일 년3", x: 0,  y: 0   },
    { key: "injY4",          label: "재해발생일 년4", x: 0,  y: 0   },
    { key: "injM1",          label: "재해발생일 월1", x: 0,  y: 0   },
    { key: "injM2",          label: "재해발생일 월2", x: 0,  y: 0   },
    { key: "injD1",          label: "재해발생일 일1", x: 0,  y: 0   },
    { key: "injD2",          label: "재해발생일 일2", x: 0,  y: 0   },
  ],
  EX_WORKER_HEALTH_EXAM: [
    { key: "ptName",           label: "성명",          x: 108, y: 705 },
    { key: "ssn",              label: "주민번호",      x: 338, y: 705 },
    { key: "address",          label: "주소",          x: 108, y: 681 },
    { key: "phone",            label: "전화번호",      x: 338, y: 681 },
    { key: "workPeriodStart",  label: "분진기간시작",  x: 108, y: 626 },
    { key: "workPeriodEnd",    label: "분진기간종료",  x: 200, y: 626 },
    { key: "workplaceName",    label: "사업장명칭",    x: 108, y: 596 },
    { key: "workplaceAddress", label: "사업장소재지",  x: 108, y: 566 },
    { key: "submitYear",       label: "년",            x: 350, y: 231 },
    { key: "submitMonth",      label: "월",            x: 390, y: 231 },
    { key: "submitDay",        label: "일",            x: 425, y: 231 },
    { key: "claimantName",     label: "신청인",        x: 300, y: 201 },
    { key: "kwc",              label: "귀하",          x: 100, y: 151 },
  ],
  DUST_WORK_CONFIRM: [
    { key: "ptName",       label: "근로자명",       x: 108, y: 766 },
    { key: "ssn",          label: "주민번호",       x: 108, y: 746 },
    { key: "ws0_company",  label: "최종_사업장명",  x: 85,  y: 696 },
    { key: "ws0_job",      label: "최종_직종명",    x: 175, y: 696 },
    { key: "ws0_dust",     label: "최종_분진명",    x: 265, y: 696 },
    { key: "ws0_startY",   label: "최종_시작년",    x: 0,   y: 0   },
    { key: "ws0_startM",   label: "최종_시작월",    x: 0,   y: 0   },
    { key: "ws0_startD",   label: "최종_시작일",    x: 0,   y: 0   },
    { key: "ws0_endY",     label: "최종_종료년",    x: 0,   y: 0   },
    { key: "ws0_endM",     label: "최종_종료월",    x: 0,   y: 0   },
    { key: "ws0_endD",     label: "최종_종료일",    x: 0,   y: 0   },
    { key: "ws1_company",  label: "과거1_사업장명", x: 85,  y: 611 },
    { key: "ws1_job",      label: "과거1_직종명",   x: 175, y: 611 },
    { key: "ws1_dust",     label: "과거1_분진명",   x: 265, y: 611 },
    { key: "ws1_startY",   label: "과거1_시작년",   x: 0,   y: 0   },
    { key: "ws1_startM",   label: "과거1_시작월",   x: 0,   y: 0   },
    { key: "ws1_startD",   label: "과거1_시작일",   x: 0,   y: 0   },
    { key: "ws1_endY",     label: "과거1_종료년",   x: 0,   y: 0   },
    { key: "ws1_endM",     label: "과거1_종료월",   x: 0,   y: 0   },
    { key: "ws1_endD",     label: "과거1_종료일",   x: 0,   y: 0   },
    { key: "ws2_company",  label: "과거2_사업장명", x: 85,  y: 530 },
    { key: "ws2_job",      label: "과거2_직종명",   x: 175, y: 530 },
    { key: "ws2_dust",     label: "과거2_분진명",   x: 265, y: 530 },
    { key: "ws2_startY",   label: "과거2_시작년",   x: 0,   y: 0   },
    { key: "ws2_startM",   label: "과거2_시작월",   x: 0,   y: 0   },
    { key: "ws2_startD",   label: "과거2_시작일",   x: 0,   y: 0   },
    { key: "ws2_endY",     label: "과거2_종료년",   x: 0,   y: 0   },
    { key: "ws2_endM",     label: "과거2_종료월",   x: 0,   y: 0   },
    { key: "ws2_endD",     label: "과거2_종료일",   x: 0,   y: 0   },
    { key: "ws3_company",  label: "과거3_사업장명", x: 85,  y: 450 },
    { key: "ws3_job",      label: "과거3_직종명",   x: 175, y: 450 },
    { key: "ws3_dust",     label: "과거3_분진명",   x: 265, y: 450 },
    { key: "ws3_startY",   label: "과거3_시작년",   x: 0,   y: 0   },
    { key: "ws3_startM",   label: "과거3_시작월",   x: 0,   y: 0   },
    { key: "ws3_startD",   label: "과거3_시작일",   x: 0,   y: 0   },
    { key: "ws3_endY",     label: "과거3_종료년",   x: 0,   y: 0   },
    { key: "ws3_endM",     label: "과거3_종료월",   x: 0,   y: 0   },
    { key: "ws3_endD",     label: "과거3_종료일",   x: 0,   y: 0   },
    { key: "ws4_company",  label: "과거4_사업장명", x: 85,  y: 370 },
    { key: "ws4_job",      label: "과거4_직종명",   x: 175, y: 370 },
    { key: "ws4_dust",     label: "과거4_분진명",   x: 265, y: 370 },
    { key: "ws4_startY",   label: "과거4_시작년",   x: 0,   y: 0   },
    { key: "ws4_startM",   label: "과거4_시작월",   x: 0,   y: 0   },
    { key: "ws4_startD",   label: "과거4_시작일",   x: 0,   y: 0   },
    { key: "ws4_endY",     label: "과거4_종료년",   x: 0,   y: 0   },
    { key: "ws4_endM",     label: "과거4_종료월",   x: 0,   y: 0   },
    { key: "ws4_endD",     label: "과거4_종료일",   x: 0,   y: 0   },
    { key: "submitYear",   label: "년",             x: 340, y: 161 },
    { key: "submitMonth",  label: "월",             x: 380, y: 161 },
    { key: "submitDay",    label: "일",             x: 415, y: 161 },
    { key: "ptSign",       label: "근로자명서명",   x: 300, y: 143 },
  ],
}

export const FORM_PDF_MAP: Record<string, string> = {
  DISABILITY_CLAIM:     'disability_claim.pdf',
  NOISE_WORK_CONFIRM:   'noise_work_confirm.pdf',
  AGENT_APPOINTMENT:    'agent_appointment.pdf',
  POWER_OF_ATTORNEY:    'power_of_attorney.pdf',
  SPECIAL_CLINIC:       'special_clinic.pdf',
  EXPERT_CLINIC:        'expert_clinic.pdf',
  WORK_HISTORY:         'work_history.pdf',
  INFO_DISCLOSURE:      'info_disclosure.pdf',
  LABOR_ATTORNEY_RECORD:'labor_attorney_record.pdf',
  THIRD_PARTY_INFO:     'third_party_info.pdf',
  MEDICAL_BENEFIT:      'medical_benefit.pdf',
  SICK_LEAVE_BENEFIT:   'sick_leave_benefit.pdf',
  INFO_DISCLOSURE_PROXY:'info_disclosure_proxy.pdf',
  PENSION_CHOICE:       'pension_choice.pdf',
  BEREAVED_CLAIM:       'bereaved_claim.pdf',
  EX_WORKER_HEALTH_EXAM:'ex_worker_health_exam.pdf',
  DUST_WORK_CONFIRM:    'dust_work_confirm.pdf',
}
